[Commit Code] - Date: 22/08/2024 13:11

diff --git a/.github/workflows/api-gateway-deploy.yml b/.github/workflows/api-gateway-deploy.yml
--- a/.github/workflows/api-gateway-deploy.yml
+++ b/.github/workflows/api-gateway-deploy.yml
@@ -27,7 +27,7 @@ env:
   KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
   KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
   ENVIRONMENT: ${{ github.ref == 'refs/heads/prod' && 'prod' || (github.ref == 'refs/heads/qas' && 'qas' || 'dev') }}
-  KUBE_API_SERVER: 'ed60-117-1-84-148.ngrok-free.app'
+  KUBE_API_SERVER: 'kubernetes.docker.internal'
 
 jobs:
   build:
@@ -134,10 +134,10 @@ jobs:
       - name: Print /etc/hosts
         run: cat /etc/hosts
 
-#      - name: Check Kubernetes API Server Connectivity
-#        run: |
-#          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
-#          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
+      - name: Check Kubernetes API Server Connectivity
+        run: |
+          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
+          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
 
       - name: Create Kubeconfig
         run: |
@@ -148,7 +148,6 @@ jobs:
       - name: Test Kubernetes Connectivity
         run: |
           kubectl cluster-info || echo "Kubernetes connectivity test failed"
-          curl -k https://${{ env.KUBE_API_SERVER }}/api || echo "API server test failed"
 
 #      - name: Install KinD
 #        run: |
