[Commit Code] - Date: 22/08/2024 16:19

diff --git a/.github/workflows/api-gateway-deploy.yml b/.github/workflows/api-gateway-deploy.yml
--- a/.github/workflows/api-gateway-deploy.yml
+++ b/.github/workflows/api-gateway-deploy.yml
@@ -77,12 +77,12 @@ jobs:
         run: echo "${{ env.DOCKER_PASSWORD }}" | docker login ${{ env.DOCKER_REGISTRY }} -u "${{ env.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build and push Docker images
-        if: env.CHANGED_SERVICES == '${{ env.APP_SERVICE }}'
+        if: env.CHANGED_SERVICES == ${{ env.APP_SERVICE }}
         run: |
           echo "Building gradle ${{ env.APP_SERVICE }}"
           cd ${{ env.APP_SERVICE }} || exit 1 # Ensure directory exists
           # Run Gradle build
-          ./gradlew build || exit 1
+          # ./gradlew build || exit 1
 
           # Verify if JAR exists
           ls -l build/libs/
@@ -165,16 +165,16 @@ jobs:
           kubectl config use-context ${{ env.APP_SERVICE }}-cluster
           cat $HOME/.kube/config # Debug: Verify the Kubeconfig content
 
-      - name: Check Kubernetes API Server Connectivity
-        run: |
-          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
-          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
+#      - name: Check Kubernetes API Server Connectivity
+#        run: |
+#          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
+#          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
 
-      - name: Create Kubeconfig
-        run: |
-          mkdir -p $HOME/.kube
-          echo "${{ env.KUBE_CONFIG }}" > $HOME/.kube/config
-          kubectl config use-context docker-desktop
+#      - name: Create Kubeconfig
+#        run: |
+#          mkdir -p $HOME/.kube
+#          echo "${{ env.KUBE_CONFIG }}" > $HOME/.kube/config
+#          kubectl config use-context docker-desktop
 
       - name: List Kubernetes nodes
         run: kubectl get nodes -v=10
@@ -184,7 +184,7 @@ jobs:
           kubectl cluster-info || echo "Kubernetes connectivity test failed"
 
       - name: Deploy to Kubernetes
-        if: env.CHANGED_SERVICES == '${{ env.APP_SERVICE }}'
+        if: env.CHANGED_SERVICES == ${{ env.APP_SERVICE }}
         run: |
           echo "Deploying ${{ env.APP_SERVICE }} to environment: ${{ env.ENVIRONMENT }}, namespace: ${{ env.KUBE_NAMESPACE }}"
           
@@ -216,6 +216,6 @@ jobs:
           fi
 
       - name: Check deployment status
-        if: env.CHANGED_SERVICES == '${{ env.APP_SERVICE }}'
+        if: env.CHANGED_SERVICES == ${{ env.APP_SERVICE }}
         run: |
           kubectl rollout status deployment/${{ env.APP_SERVICE }} --namespace=${{ env.KUBE_NAMESPACE }} || true
