[Commit Code] - Date: 22/08/2024 13:07

diff --git a/.github/workflows/api-gateway-deploy.yml b/.github/workflows/api-gateway-deploy.yml
--- a/.github/workflows/api-gateway-deploy.yml
+++ b/.github/workflows/api-gateway-deploy.yml
@@ -134,10 +134,10 @@ jobs:
       - name: Print /etc/hosts
         run: cat /etc/hosts
 
-      - name: Check Kubernetes API Server Connectivity
-        run: |
-          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
-          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
+#      - name: Check Kubernetes API Server Connectivity
+#        run: |
+#          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
+#          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
 
       - name: Create Kubeconfig
         run: |
