[Commit Code] - Date: 22/08/2024 16:40

diff --git a/.github/workflows/api-gateway-deploy.yml b/.github/workflows/api-gateway-deploy.yml
--- a/.github/workflows/api-gateway-deploy.yml
+++ b/.github/workflows/api-gateway-deploy.yml
@@ -151,9 +151,9 @@ jobs:
       - name: Create KinD Cluster
         run: |
           if kind get clusters | grep -q "api-gateway-cluster"; then
-            echo "KinD cluster 'api-gateway-cluster' already exists."
+            echo "KinD cluster '${{ env.APP_SERVICE }}-cluster' already exists."
           else
-            echo "Creating KinD cluster 'api-gateway-cluster'..."
+            echo "Creating KinD cluster '${{ env.APP_SERVICE }}-cluster'..."
             kind create cluster --name api-gateway-cluster
           fi
 
@@ -162,19 +162,19 @@ jobs:
           mkdir -p $HOME/.kube
           echo "Exporting KinD Kubeconfig"
           kind get kubeconfig --name api-gateway-cluster > $HOME/.kube/config
-          kubectl config use-context kind-api-gateway-cluster
+          kubectl config use-context api-gateway-cluster
           cat $HOME/.kube/config # Debug: Verify the kubeconfig content
 
-#      - name: Check Kubernetes API Server Connectivity
-#        run: |
-#          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
-#          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
+      - name: Check Kubernetes API Server Connectivity
+        run: |
+          echo "Pinging Kubernetes API Server: ${{ env.KUBE_API_SERVER }}"
+          ping -c 4 ${{ env.KUBE_API_SERVER }} || echo "Ping failed"
 
-#      - name: Create Kubeconfig
-#        run: |
-#          mkdir -p $HOME/.kube
-#          echo "${{ env.KUBE_CONFIG }}" > $HOME/.kube/config
-#          kubectl config use-context docker-desktop
+      - name: Create Kubeconfig
+        run: |
+          mkdir -p $HOME/.kube
+          echo "${{ env.KUBE_CONFIG }}" > $HOME/.kube/config
+          kubectl config use-context docker-desktop
 
       - name: List Kubernetes nodes
         run: kubectl get nodes -v=10
